'use client'
import {useState} from 'react'
const rounds=[
{type:'phish',tag:'01 / PHISHING',title:'Spot the attack',text:'URGENT: Your college Microsoft 365 account will be suspended today. We detected unusual login activity. Verify your account within 30 minutes to prevent suspension. [Verify Account → security-verify.example]',choices:['Legitimate — verify now','Suspicious — inspect the sender/link','Legitimate — forward to a friend'],answer:1,why:'Urgency, account-threat language and a suspicious verification domain are classic phishing signals.'},
{type:'social',tag:'02 / SOCIAL ENGINEERING',title:'The CEO text',text:'“I’m in a meeting and can’t take calls. Please buy 3 gift cards worth KSh 10,000 each and send me the codes ASAP. I’ll reimburse you.”',choices:['Buy them immediately','Call the CEO using a known number to verify','Ask for the CEO’s personal email'],answer:1,why:'A known communication channel breaks the impersonation loop. Never rely on the message itself for verification.'},
{type:'breach',tag:'03 / BREACH RESPONSE',title:'Someone clicked',text:'A staff member clicked a suspicious link and entered their password. What should happen FIRST?',choices:['Delete the browser history','Change the password and report the incident immediately','Wait to see if anything happens'],answer:1,why:'Fast reporting and credential containment reduce the attacker’s window of opportunity.'},
{type:'ai',tag:'04 / AI DETECTOR',title:'Human or AI?',text:'“Congratulations! You have been selected for an exclusive scholarship opportunity. Click here within 15 minutes to claim your award.”',choices:['Probably safe','Probably AI-generated / scam content','Impossible to tell, so click it'],answer:1,why:'AI can produce polished bait at scale, but the real signal is the pressure + unsolicited reward + suspicious action.'},
{type:'defend',tag:'05 / AI VS AI',title:'Build your defense',text:'An attacker has AI that can write convincing messages in seconds. Which defense gives your organization the strongest advantage?',choices:['Train people to verify unusual requests','Assume AI-written messages are always fake','Give everyone the same password'],answer:0,why:'AI strengthens both sides. Human verification habits, layered controls and reporting processes keep the defender ahead.'}
]
export default function Home(){const [screen,setScreen]=useState('home');const [name,setName]=useState('');const [side,setSide]=useState('');const [i,setI]=useState(0);const [score,setScore]=useState(0);const [picked,setPicked]=useState(null);const r=rounds[i];
function start(s){setSide(s);setScreen('game');setI(0);setScore(0);setPicked(null)}
function choose(n){if(picked!==null)return;setPicked(n);if(n===r.answer)setScore(x=>x+100)}
function next(){if(i<rounds.length-1){setI(x=>x+1);setPicked(null)}else setScreen('done')}
return <main><header><div className="brand">CYBER<span>//</span>WAR</div><div className="status">AI VS AI <b>● LIVE</b></div></header>
{screen==='home'&&<section className="hero"><div className="eyebrow">INTERACTIVE CYBERSECURITY EXPERIENCE</div><h1>AI is the weapon.<br/><em>Who controls it?</em></h1><p>Test your instincts against five rapid-fire cyber attacks. Play on your phone. No accounts. No real credentials.</p><div className="join"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your codename"/><button onClick={()=>name.trim()&&setScreen('side')}>ENTER THE WAR →</button></div><div className="stats"><span>05 ROUNDS</span><span>100 PTS / HIT</span><span>5 MINUTES</span></div></section>}
{screen==='side'&&<section className="panel"><div className="eyebrow">CHOOSE YOUR SIDE</div><h2>Attack or defend.</h2><p>Both sides use AI. Your decisions determine who wins.</p><div className="sides"><button className="side red" onClick={()=>start('ATTACKER')}><strong>🔴 ATTACK</strong><small>Think like the threat actor</small></button><button className="side blue" onClick={()=>start('DEFENDER')}><strong>🔵 DEFEND</strong><small>Think like the security team</small></button></div></section>}
{screen==='game'&&<section className="game"><div className="gamehead"><div><div className="eyebrow">{r.tag}</div><h2>{r.title}</h2></div><div className="score">{score}<small>PTS</small></div></div><div className="progress"><i style={{width:`${((i+1)/rounds.length)*100}%`}}/></div><div className="scenario"><label>SCENARIO</label><p>{r.text}</p></div><div className="choices">{r.choices.map((c,n)=><button key={c} className={picked!==null?(n===r.answer?'correct':n===picked?'wrong':'dim'):''} onClick={()=>choose(n)}><span>{String.fromCharCode(65+n)}</span>{c}</button>)}</div>{picked!==null&&<div className={'feedback '+(picked===r.answer?'good':'bad')}><strong>{picked===r.answer?'✓ CORRECT':'✕ NOT QUITE'}</strong><p>{r.why}</p><button onClick={next}>{i===rounds.length-1?'SEE RESULTS':'NEXT ROUND →'}</button></div>}</section>}
{screen==='done'&&<section className="panel done"><div className="eyebrow">MISSION COMPLETE</div><h2>{score>=400?'🛡️ DEFENDER WINS':'⚠️ THE ATTACKER GOT THROUGH'}</h2><div className="bigscore">{score}<span>/ 500</span></div><p>{score>=400?'Excellent instincts. The best cybersecurity teams combine AI speed with human judgment.':'AI-powered attacks move fast. Slow down, verify, report and use AI as a defender — not as an autopilot.'}</p><button onClick={()=>setScreen('home')}>PLAY AGAIN →</button></section>}
<footer><span>AFRICA TECH SPACE</span><span>RESPONSIBLE AI • CYBERSECURITY WORKSHOP</span></footer></main>}
